### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by Antonboom** [ryancurrah/gomodguard#21]
Hello!

Repo: https://github.com/OtusGolang/home_work

Package: https://github.com/OtusGolang/home_work/tree/master/hw01_hello_otus

```
▶ gomodguard ./hw01_hello_otus/...
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x10051781c]

goroutine 1 [running]:
github.com/ryancurrah/gomodguard.(*Processor).SetBlockedModules(0x14000136408)
        /Users/anthony/golang_workspace/pkg/mod/github.com/ryancurrah/gomodguard@v1.2.2/gomodguard.go:368 +0x5c
github.com/ryancurrah/gomodguard.NewProcessor(0x1400019a460, 0x20, 0x1400019a400, 0x1400012a010)
        /Users/anthony/golang_workspace/pkg/mod/github.com/ryancurrah/gomodguard@v1.2.2/gomodguard.go:290 +0x1c0
github.com/ryancurrah/gomodguard.Run(0x100563a00)
        /Users/anthony/golang_workspace/pkg/mod/github.com/ryancurrah/gomodguard@v1.2.2/cmd.go:85 +0x6b8
main.main()
        /Users/anthony/golang_workspace/pkg/mod/github.com/ryancurrah/gomodguard@v1.2.2/cmd/gomodguard/main.go:10 +0x20
```

**Comment by ryancurrah** [comment]
The `go.mod` file must be in the current working directory for it to work, I recommend disabling the linter. I did push a change for the panic. Instead of panicking an error will be reported telling the user, they must have the `go.mod` file in the current working directory.

**Comment by ryancurrah** [comment]
https://github.com/ryancurrah/gomodguard/commit/0decae5e66a21da9ca569652a9cf3d211f52017e

**Comment by Antonboom** [comment]
Thank u!
